zhobe:
    ttyh:
        restart_timeout: 3s
        root: "/path/to/root/"
        jabber:
            jid:        "test@example.tld/resource"
            password:   "password"
            conference: "ttyh@conference.example.org"
            nickname:   "BotNickname"
            skip_tls:    True
        gsend:
            listen: "127.0.0.1:4042"
            secret: "secret_to_send_shit"
